### ISSUE TITLE
Feature Request: Signal which only sends once

### ISSUE THREAD

**Issue by kasium** [pallets-eco/blinker#129]
Hi, I have a use-case of having a signal which only sends once. Currently I solve this, by subclassing `Signal` and having a boolean instance variable which is set to true if `send` is called. If then `send` is called again and the boolean value is true, no real sending is performend. 

IMHO, this would be a nice feature for this project and I'm happy to contribute. I opened this issue before to ask if you share my view or not (opinions differ which is fine)

**Comment by davidism** [comment]
You can already build this if you need it, either as you've shown or perhaps in a way that unregisters itself on call. I don't think it's a good enough pattern to encourage for general use though.
