### ISSUE TITLE
@_utilities.lazy_property isn't thread safe

### ISSUE THREAD

**Issue by harlowja** [pallets-eco/blinker#21]
Just thought I'd let u know (from having made this same mistake myself),

But the application of `@_utilities.lazy_property` isn't actually thread-safe.

An example program you can try:

```
import threading
import thread

import time

from blinker import _utilities


class SlowThing(object):

    @_utilities.lazy_property
    def b(self):
        print "starting reading 'b' thread %s" % thread.get_ident()
        time.sleep(0.5)
        print "finished reading 'b' thread %s" % thread.get_ident()
        return 1

s = SlowThing()


def _run():
    s.b


threads = []
for i in range(0, 5):
    t = threading.Thread(target=_run)
    threads.append(t)
    t.start()


while threads:
    t = threads.pop()
    t.join()

```

The output of this will create:

```
starting reading 'b' thread 140684440516352
starting reading 'b' thread 140684432123648
starting reading 'b' thread 140684423730944
starting reading 'b' thread 140684415338240
starting reading 'b' thread 140684203915008
finished reading 'b' thread 140684432123648
finished reading 'b' thread 140684440516352
finished reading 'b' thread 140684423730944
finished reading 'b' thread 140684415338240
finished reading 'b' thread 140684203915008
```

So u can see there are many threads at the same time recomputing that property (in this case it doesn't matter, but in other cases it might?)

Some code that I have made that does appear to work fine:

Perhaps we can share it somehow...

https://github.com/openstack/taskflow/blob/master/taskflow/utils/misc.py#L346

**Comment by jek** [comment]
I'm curious: did you hit this thread safety issue using blinker, or is it an observation from viewing the code? If in blinker, you must have a pretty interesting use case to hit thread safety on `lazy_property`, given it's very sparing application on a couple meta-signals.

Regardless, those the two `lazy_property` uses are returning objects with useful identity (vs. strings or ints etc.), so switching the memoization implementation from `setattr` to `__dict__.setdefault` is probably in order.

**Comment by harlowja** [comment]
Mostly just an observation from building a similar piece of code.

On Sunday, September 20, 2015, jason kirtland <notifications@github.com>
wrote:

> I'm curious: did you hit this thread safety issue using blinker, or is it
> an observation from viewing the code? If in blinker, you must have a pretty
> interesting use case to hit thread safety on lazy_property, given it's
> very sparing application on a couple meta-signals.
>
> Regardless, those the two lazy_property uses are returning objects with
> useful identity (vs. strings or ints etc.), so switching the memoization
> implementation from setattr to __dict__.setdefault is probably in order.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jek/blinker/issues/21#issuecomment-141820984>.
>


-- 
--
facebook.com/jshharlow <http://www.facebook.com/jshharlow>
flickr.com/jshharlow
YIM: jshharlow
