### ISSUE TITLE
Support for receivers without positional parameters?

### ISSUE THREAD

**Issue by thegreathippo** [pallets-eco/blinker#28]
On one of the things I'm working on, blinker.py seems like a perfect solution -- if I could connect receivers that don't take any positional or keyword arguments. That way, I could integrate blinker without having to add an empty positional just to provide access. The necessary modification for this seems fairly light-weight and potentially useful in several cases -- but I'm wondering if it might create unforeseen problems.

In blinker/base.py:

```
def _get_ret_val(func, val, **kwargs):
    try:
        ret_val = func(val, **kwargs)
    except TypeError:
        if val is None:
            ret_val = func(**kwargs)
        else:
            raise
    return ret_val
```

Then, adding it to the final statement in Signal.send...

```
    def send(self, *sender, **kwargs):
        if len(sender) == 0:
            sender = None
        elif len(sender) > 1:
            raise TypeError('send() accepts only one positional argument, '
                            '%s given' % len(sender))
        else:
            sender = sender[0]
        if not self.receivers:
            return []
        else:
            return [(receiver, _get_ret_val(receiver, sender, **kwargs))
                    for receiver in self.receivers_for(sender)]
```

The only problem with this I can think of is that None sender might carry special significance; does it?

(Apologies in advance if this is not the place to ask these questions; I'm a bit new to this!)

**Comment by davidism** [comment]
I don't plan to add this sort of signature checking. Receiver functions are intended to get the sender as the first positional argument, and that keeps the API and implementation simple. If you want to reuse an existing function for a receiver without changing its signature, you can write a fairly trivial wrapper for it.

```
from functools import update_wrapper

def as_receiver(f):
    def wrapper(sender, **kwargs):
        return f(**kwargs)
    return update_wrapper(wrapper, f)

my_receiver = as_receiver(my_func)
my_signal.connect(my_receiver)
```
