### ISSUE TITLE
Release new version to PyPI

### ISSUE THREAD

**Issue by DonDebonair** [pallets-eco/blinker#36]
There have been several fixes on master since the last release (1.4). Could you release a new version to PyPI?

**Comment by jek** [comment]
There are no fixes on master since 1.4, but it is probably near time for a release regardless.

**Comment by DandyDev** [comment]
I see at least 2 commits that are not in an official release yet:

https://github.com/jek/blinker/commit/364a389405e337889ea17bc8770ad3dc691803cb

https://github.com/jek/blinker/commit/42aad6110a02a86a9a51a77c75c2d638a50656b7

And I would also suggest including https://github.com/jek/blinker/pull/31

**Comment by jek** [comment]
Yes, but neither of these are fixes. I'll take a look at #31.

**Comment by ThomasWaldmann** [comment]
Just as a note: there is the idea of moving to `discorporate/blinker` on github. If this is wanted, maybe do it before next release, so the docs and pypi metadata of that release can already link to the new location.

**Comment by AbdealiJK** [comment]
Any plans on releasing ? 
I personally was looking for the recent addition of async signals

**Comment by johnthagen** [comment]
Wheels (`.whl`) for this package are [currently missing from PyPI](https://pypi.org/project/blinker/#files). Could wheels be uploaded for the current and future releases?

Read more about the [advantages of wheels](https://pythonwheels.com/) to understand why generating wheel distributions are important.

To create a wheel along with source distribution:

```bash
(venv) $ pip install --upgrade pip setuptools wheel
(venv) $ python setup.py sdist bdist_wheel

# See dist/*.whl
```

To upload wheels:

```bash
(venv) $ pip install twine
(venv) $ twine upload dist/*
```

**Comment by JulienPalard** [comment]
I'll also be happy to see a release too, in my case because I spotted a warning fixed 2 years ago in 194e17a20008bd778714182ac191ad654074f81c.

Thanks @jek for Blinker while I'm here \o/ (It's used by https://pypi.org/project/oauthlib/, so it's used by `from google_auth_oauthlib.flow import InstalledAppFlow`).

**Comment by davidism** [comment]
Blinker has moved to Pallets-Eco, a place for community maintenance of projects related to the Pallets projects (Flask, etc). If anyone is actively using this project and is interested in helping maintain it, please message us on our Discord server: https://discord.gg/pallets.

**Comment by ThomasWaldmann** [comment]
@davidism why does a move "close this ticket as completed"? Latest pypi release is still from 2015.

So I guess a release is still needed, now even more for updating the project URLs in the pypi package, please reopen.
