### ISSUE TITLE
Needed a queued connection

### ISSUE THREAD

**Issue by Felix-neko** [pallets-eco/blinker#4]
Sometimes I have a coil-like topology of objects. In Qt I just used QueuedConnection signal connection for them. Cannot you implement something like that?

```
import blinker
from blinker import Signal


mega_signal = Signal()

   class QueuedObject(object):

    def __init__(self):
        self.counter = 0

    def on_received(self, *args):
        print(self.counter)
        self.counter += 1
        if self.counter <= 50000:
            mega_signal.send()


foo = QueuedObject()

mega_signal.connect(foo.on_received)
mega_signal.send()
```

**Comment by jek** [comment]
I'm not familiar with Qt. The docs suggest that QueuedConnection causes the signal reception to occur in the recipient's thread asynchronously. But from your example I'm not sure that's what you're after. Can you elaborate?
