### ISSUE TITLE
Blocking API / waiting API?

### ISSUE THREAD

**Issue by boompig** [pallets-eco/blinker#40]
Is there any support to execute a blocking wait for a specific signal or signals?

Usecase: agent-based modelling where the agents communicate

**Comment by davidism** [comment]
I don't think this makes sense in the context of this library. This library doesn't deal with threads or coroutines, it only cares about registering callbacks that will be called when the signal is sent. Waiting for the signal to be sent could be done with some sort of thread that registers a handler that sets a value, then waiting on that value, but at that point you may as well use a `threading.Event` directly, or use `async/await` coroutines.
