### ISSUE TITLE
add type hints to the project

### ISSUE THREAD

**Issue by bbc2** [pallets-eco/blinker#43]
Having type hints for this library would make it possible to check its usage in applications with Mypy.  I currently have a [work-in-progress](https://github.com/python/typeshed/compare/master...bbc2:blinker-stubs?expand=1) of those type hints.

Before it can be accepted into python/typeshed, I need to get [the permission from the maintainers](https://github.com/python/typeshed/blob/master/CONTRIBUTING.md#adding-a-new-library), so is it OK if I submit Blinker stubs to typeshed?

**Comment by miki725** [comment]
this would be a super useful feature

**Comment by jek** [comment]
sorry I missed this: please feel free to submit to typeshed. also I'm very amenable to a patch that adds hints to the blinker project.

**Comment by davidism** [comment]
I'll add types to the code, don't add them to typeshed.

**Comment by kasium** [comment]
@davidism any update on this? I can try to support if you like 😄

**Comment by Secrus** [comment]
@davidism I am also happy to help push this project into modern standards (started some work at #77 and #78)

**Comment by sjaq** [comment]
If there's any need for help I'd be willing to spend some time on this as well, or are you still picking this up @davidism?

**Comment by Secrus** [comment]
> If there's any need for help I'd be willing to spend some time on this as well, or are you still picking this up @davidism?

I am actively working on it right now. No need to start it on your end as well @sjaq

**Comment by pgjones** [comment]
1.6.1, now released, has initial type hints.
