### ISSUE TITLE
move to github.com/discorporate/blinker

### ISSUE THREAD

**Issue by ThomasWaldmann** [pallets-eco/blinker#45]
@jek iirc you can click somewhere in the settings to move a repo to a new github org.

guess that is the easiest option to get it there.

i'ld offer to do some basic maintenance if i get the permissions (like for flatland, including a new pypi release with the new URL).

**Comment by hugovk** [comment]
Alternatively, https://jazzband.co?

**Comment by sfdye** [comment]
+1 for jazzband

**Comment by sfdye** [comment]
What do you think? @jek 

If you don't have the time to maintain this project, the community can help :)

**Comment by hugovk** [comment]
If there's no reply, someone could consider a fork and a PEP 541 transfer of the PyPI name:

https://www.python.org/dev/peps/pep-0541/

**Comment by sfdye** [comment]
Let's give the owner some time to respond

**Comment by jek** [comment]
what is the need driving this request?

**Comment by sfdye** [comment]
There is no need to move this project anywhere, if the project can still be actively maintained (triaging issues/pull requests, cutting new release to PyPI, etc)

What you can help as the owner is maybe considering granting `collaborator` permission to someone like @hugovk or myself. We'd love to help move this project forward 😄

**Comment by ThomasWaldmann** [comment]
i think it is always better to have projects under some github org account than under a personal account (except, obviously, for purely personal projects or for very fresh stuff).

the reason is somehow the message that is communicated, like:
- "this is my thing", vs.
- "this a community thing maintained by this org" (which is open to all interested parties)

if one then thinks about stuff like bus factor and long term maintenance, the org way gets even better.

of course it still needs people actually doing something good for the project, but at least it is more "inviting".

**Comment by jek** [comment]
I am very open to passing the torch on this project (lead or collaborator) to anyone working in this space with the cross-implemention know-how (especially understanding of which operations are atomic across Python implementations) and, crucially, can articulate why send_robust does not belong in the core.

**Comment by delijati** [comment]
`send_robust` seams legit to me. It does not change existing api it only extends it and there are tests for it. So can this process of moving the repo or releasing at least a new version be triggered again.

**Comment by davidism** [comment]
Blinker has moved to Pallets-Eco, a place for community maintenance of projects related to the Pallets projects (Flask, etc). If anyone is actively using this project and is interested in helping maintain it, please message us on our Discord server: https://discord.gg/pallets.
