### ISSUE TITLE
Project Active?

### ISSUE THREAD

**Issue by rmad17** [pallets-eco/blinker#50]
Is this project still active? I am asking this since I see lot of old pending PRs.

**Comment by guy881** [comment]
@jek any future plans for the project?

**Comment by sfdye** [comment]
See #45

**Comment by davidism** [comment]
Blinker has moved to Pallets-Eco, a place for community maintenance of projects related to the Pallets projects (Flask, etc). If anyone is actively using this project and is interested in helping maintain it, please message us on our Discord server: https://discord.gg/pallets.
