### ISSUE TITLE
NameError: name 'Exception' is not defined

### ISSUE THREAD

**Issue by jmprovencher** [pallets-eco/blinker#52]
`Exception ignored in: <function BoundMethodWeakref.__init__.<locals>.remove at 0x7f6a4404cae8>
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/blinker/_saferef.py", line 174, in remove
NameError: name 'Exception' is not defined
Exception ignored in: <function BoundMethodWeakref.__init__.<locals>.remove at 0x7f6a4404ca60>
Traceback (most recent call last):
  File "/opt/python/run/venv/local/lib/python3.6/site-packages/blinker/_saferef.py", line 174, in remove
NameError: name 'Exception' is not defined`

I think the line 174 `except Exception:` in https://github.com/jek/blinker/blob/master/blinker/_saferef.py shoud be only except: in python 3.

**Comment by davidism** [comment]
I don't see this error when using Blinker with Flask. `Exception` is defined in Python 3, a bare `except` does not have the same meaning and shouldn't be required. Please provide a minimal reproducible example if you're still having this issue.
