### ISSUE TITLE
Support multiple senders in connect_via

### ISSUE THREAD

**Issue by sfdye** [pallets-eco/blinker#56]
https://pythonhosted.org/blinker/#blinker.base.Signal.connect_via

We have a use case to send a 	signal to multiple senders, so we can do:
```
@some_signal.connect_via_multiple([sender1, sender2, ..., senderN])
def func():
	pass

# instead of
@some_signal.connect_via(sender1)
@some_signal.connect_via(sender2)
...
@some_signal.connect_via(senderN)

def func():
	pass
```

@jek Would like to get some opinion from you. Are you leaning on adding a new method `connect_via_multiple` that does the same thing as `connect_via` except that it accepts `senders` as a list, or updating the current `connect_via` to accept a senders as either a single sender or list of senders? I will be happy to throw in a PR.

**Comment by davidism** [comment]
I think it's fine to just use `connect_via` multiple times. If your specific use case requires a large number of these, it might indicate that some other refactor in your code might be appropriate, or you could use other strategies like a `for` loop or a custom decorator around this decorator.
