### ISSUE TITLE
Is dispatch_uid required?

### ISSUE THREAD

**Issue by maziar-dandc** [pallets-eco/blinker#79]
Is dispatch_uid functionality required to reach a feature parity with django signals, or does blinker automatically ensures that's not needed?

I'm basically replacing django.db signals with mongoengine ones, and I want to make sure I'm not introducing bugs because of a missing feature.

![image](https://user-images.githubusercontent.com/53433222/199659753-c895f85f-56cb-4380-91a3-d9507717121d.png)

https://docs.djangoproject.com/en/4.1/topics/signals/#listening-to-signals
https://docs.djangoproject.com/en/4.1/topics/signals/#preventing-duplicate-signals

**Comment by davidism** [comment]
Sorry, I can't do this sort of code analysis for you. Blinker does in fact work, and does have a different implementation than Django. I'll leave it to you to audit both code bases regarding this.
