### ISSUE TITLE
Use of ParamSpec only works in Python 3.10+

### ISSUE THREAD

**Issue by luong-komorebi** [pallets-eco/blinker#90]
This morning we faced this issue 
![42580](https://user-images.githubusercontent.com/15828926/229389777-a094d85e-4de1-4264-93f8-1c7d53d8b2e5.png)

for a working service that has received no code change in dependencies recently. By tracking the root cause, I was able to detect that it was caused by typing-extension, which was used by blinker, which was part of Flask (our direct dependency). A similar issue with the same footprint could be found [here](https://github.com/HypothesisWorks/hypothesis/issues/3397) and [here](https://stackoverflow.com/questions/72980064/from-typing-extensions-import-paramspec-importerror-cannot-import-name-paramsp). Typing extension didnt include a change log for version < 4 so I cannot track down which version starts this issue. 

We either need to do some if else check to ensure that when a combination of packages is used, blinker is able to use paramspec. Another intrusive way is to declare a minimum version for typing extension.

**Comment by davidism** [comment]
> Another intrusive way is to declare a minimum version for typing extension.

Yes, this is the correct way. It sounds like you already had a version of typing_extensions installed, which was not upgraded when you installed Flask-SQLAlchemy. Since we depend on features from a later version, we should set that minimum version.

**Comment by pgjones** [comment]
I think I'll require ParamSpec > 4.2 (first mention of ParamSpec), and I'll release a 1.6.1 to fix this and the missing `py.typed` file.

**Comment by pgjones** [comment]
Fixed with 1.6.1, now released.
